export const items =  [
    {
      id: 1,
      category: 'Lodge',
      title: "Pawan Lodge, Millan Chowk",
      imgSrc: '/pl.jpg',
      imgSrc1: '/pl1.jpg',
      imgSrc2: '/pl2.jpg',
      imgSrc3: '/pl3.jpg',
      address: 'Mankideepka Near Chair Factory',
      description: 'Single Room Available',
    },
    {
      id: 2,
      category: 'Mess',
      title: "Mahto Hotel Mess, Millan Chowk",
      imgSrc: '/mm.jpeg',
      imgSrc1: '/nani.jpeg',
      imgSrc2: '/mahto.jpeg',
      imgSrc3: '/aahar.jpeg',
      address: 'Millan Chowk, Near FCI Godown',
      description: 'Tasty and Healthy Food.',
    },
    {
      id: 3,
      category: 'Mess',
      title: "Chachi Hotel Mess, Millan Chowk",
      imgSrc: '/nani.jpeg',
      imgSrc1: '/nani.jpeg',
      imgSrc2: '/mahto.jpeg',
      imgSrc3: '/aahar.jpeg',
      address: 'Millan Chowk, Near CIT Gate',
      description: 'Tasty and Healthy Food.',
    },
    {
      id: 4,
      category: 'Lodge',
      title: "Durga Lodge, Millan Chowk",
      imgSrc: '/dl.jpg',
      imgSrc1: '/dl1.jpg',
      imgSrc2: '/dl2.jpg',
      imgSrc3: '/dl1.jpg',
      address: 'Millan Chowk, Near Ravi Hotel',
      description: 'Single Rooms Available.',
    },
    {
      id: 5,
      category: 'Lodge',
      title: "Manesh Lodge, Millan Chowk",
      imgSrc: '/ml.jpeg',
      imgSrc1: '/dl1.jpg',
      imgSrc2: '/dl2.jpg',
      imgSrc3: '/dl1.jpg',
      address: 'Mankideepka Near Chair Factory',
      description: 'Single Rooms Available.',
    },
    {
      id: 7,
      category: 'Mess',
      title: "Aahar Hotel Mess,  Tatisilwai",
      imgSrc: '/aahar.jpeg',
      imgSrc1: '/nani.jpeg',
      imgSrc2: '/mahto.jpeg',
      imgSrc3: '/aahar.jpeg',
      description: 'Tasty and Healthy Food.',
    },

  ]